version: "3"
services:
  automation:
    image: gcr.io/${PROJECT_ID}/testautomation:latest
    container_name: automation-test
    environment:
      - PROJ=Projects/${PROJECT_NAME}
      - RELEASE=${RELEASE_NAME}
      - TESTSET=${TESTSET_NAME}
      - GRIDURL=${GRID_URL}    
    volumes:
      - ./Results/:/workspace/Projects/${PROJECT_NAME}/Results/TestExecution/${RELEASE_NAME}/${TESTSET_NAME}